# Generated by Django 5.1.3 on 2024-12-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Cook', 'Cook'), ('Code', 'Code'), ('Change', 'Change')], default='Cook', max_length=10),
            preserve_default=False,
        ),
    ]
