# Generated by Django 5.1.3 on 2024-12-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords separate da virgole', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description per SEO (max 155 caratteri)', max_length=155),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_score',
            field=models.IntegerField(default=0, help_text='Punteggio SEO da 0 a 100'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Titolo ottimizzato per SEO (max 60 caratteri)', max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Cook', 'Cook'), ('Code', 'Code'), ('Change', 'Change')], default='Cook', max_length=50),
        ),
    ]
