# Generated by Django 5.1.3 on 2024-12-22 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_keywords_post_meta_description_post_seo_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, help_text='Parole chiave separate da virgole', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrizione che apparirà nei risultati di ricerca (max 160 caratteri)', max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Titolo ottimizzato per i motori di ricerca (max 60 caratteri)', max_length=60),
        ),
    ]
