name: Test Secrets
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ -n "${{ secrets.REMOTE_HOST }}" ]; then
            echo "REMOTE_HOST is set"
          else
            echo "REMOTE_HOST is not set"
       
   fi
#chissa
